env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_USERNAME: "Ibratabian17"
    BUILD_HOSTNAME: "Prjkt"
    USE_CCACHE: "1"
    CCACHE_EXEC: "/usr/bin/ccache"
    
task:
  name: "Building.."
  timeout_in: 240m  
  container:
      image: anyakichi/aosp-builder:bionic
      cpu: 8
      memory: 32G
        
  test_script:
       - export DEBIAN_FRONTEND=noninteractive
       - DEBIAN_FRONTEND=noninteractive > /dev/null
       - git config --global user.name "Pakar" > /dev/null
       - git config --global user.email "Pakar@gmail.com" > /dev/null
       - df -h
       - lsblk
       - ls -l -a -h
  
  sync_script:
      - mkdir android
      - cd android
      - repo init --depth=1 --no-repo-verify -u git://github.com/LineageOS/android.git -b lineage-18.1 -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/ibraaltabian17/local_manifest.git --depth 1 -b main .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync

  build_script:
      - cd android
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 150G
      - . build/envsetup.sh
      - croot
      - lunch lineage_A6020-userdebug && mka bacon -j8
     
  upload_script:
      - cd android
      - cd out/target/product/beryllium
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file *.zip https://transfer.sh | tee link.txt && echo " "
      - cat link.txt && echo " "
        

