env:
    MANIFEST: https://github.com/SwiftOS-DROID/android_manifest.git -b 12
task:
  name: "Rom Checker"
  timeout_in: 1h
  container:
      image: ubuntu:latest
      cpu: 4
      memory: 8G
      volumes:
        - /home/android:/home/android

        
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - sudo apt install build-essential lzip git zip git-lfs -y 
       - git config --global user.name "Ibratabian17"
       - git config --global user.email "ibratabian@gmail.com"
       - cd ~
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - printf "\n\n\n============================\nMemulai Build Gapps\n============================\n"
      - git clone https://github.com/opengapps/opengapps --depth=1
      - cd opengapps
      - ./download_sources.sh --shallow arm64
      - make arm64-32-pico
      - ./report_sources.sh
      - printf "\n\n\n============================\nRepository Berhasil Diunduh, Siap digunakan!!\n============================"
        
