env:
    MANIFEST: https://github.com/ArrowOS/android_manifest.git -b arrow-11.0
    DEVICE: A6020
    OEM: lenovo
    DT_LINK: https://github.com/ibratabian17/device_lenovo_A6020.git
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/ibratabian17/vendor_lenovo_A6020.git
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/hsj51/kernel_lenovo_msm8916.git
    PLATFORM: msm8916
    KT_PATH: kernel/$OEM/$PLATFORM
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: arrow_$DEVICE-userdebug

task:
  name: "Building.."
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt -q update > /dev/null
       - apt -q install sudo > /dev/null
       - DEBIAN_FRONTEND=noninteractive apt-get -q install -y --no-install-recommends tzdata > /dev/null
       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
       - apt-get -q install -y tzdata > /dev/null
       - dpkg-reconfigure --frontend noninteractive tzdata > /dev/null
       - sudo apt -q update -y && sudo apt -q install git aria2 curl wget rsync zip unzip lzma cpio ccache clang jq -y > /dev/null
       - sudo apt -q install python3 -y > /dev/null
       - sudo ln -sf /usr/bin/python3 /usr/bin/python 
       - git config --global user.name "Pakar" > /dev/null
       - git config --global user.email "Pakar@gmail.com" > /dev/null
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts > /dev/null
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh > /dev/null
       - cd ~
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p /home/android/os
      - cd /home/android/os
      - repo init --depth=1 --no-repo-verify -u $MANIFEST -g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - git clone $DT_LINK $DT_PATH
      - git clone $VT_LINK $VT_PATH
      - git clone $KT_LINK $KT_PATH
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd /home/android/os
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 400G
      - . build/envsetup.sh
      - lunch $LUNCH_COMBO
      - mka $TARGET -j8
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd /home/android/os
      - cd out/target/product/$DEVICE
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file *.zip https://transfer.sh | tee link.txt && echo " "
      - rm -rm *.zip
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        

