env:
    MANIFEST: https://github.com/SwiftOS-ROM/android_manifest.git -b 11-tmp
task:
  name: "Rom Checker"
  timeout_in: 1h
  container:
      image: anyakichi/aosp-builder:bionic
      cpu: 8
      memory: 32G

        
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - git config --global user.name "Ibratabian17"
       - git config --global user.email "ibratabian@gmail.com"
       - cd ~
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - printf "\n\n\n============================\nMemulai Cek Repositori\n============================\n"
      - mkdir -p /home/android
      - cd /home/android
      - repo init -u $MANIFEST
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - git clone https://github.com/SwiftOS-Devices/android_device_xiaomi_lava && git clone https://github.com/Redmi-MT6768/android_vendor_xiaomi_lava -b eleven vendor/xiaomi/lava && git clone https://github.com/Redmi-MT6768/android_kernel_xiaomi_mt6768 -b eleven kernel/xiaomi/mt6768 && git clone https://github.com/PixelExperience/device_mediatek_sepolicy_vndr -b eleven device/mediatek/sepolicy_vndr && git clone https://github.com/Redmi-MT6768/android_device_xiaomi_mt6768-common -b eleven device/xiaomi/mt6768-common
      - printf "\n\n\n============================\nRepository Berhasil Diunduh, Siap digunakan!!\n============================"
        
  Build_script:
      - . build/envsetup.sh && lunch swift_lava-userdebug && mka bacon
