env:
    MANIFEST: https://github.com/SwiftOS-ROM/android_manifest.git -b 11-tmp
task:
  name: "Rom Checker"
  timeout_in: 1h
  container:
      image: anyakichi/aosp-builder:bionic
      cpu: 8
      memory: 32G
      volumes:
        - /home/android:/home/android

        
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - git config --global user.name "Ibratabian17"
       - git config --global user.email "ibratabian@gmail.com"
       - cd ~
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - printf "\n\n\n============================\nMemulai Cek Repositori\n============================\n"
      - mkdir -p /home/android
      - cd /home/android
      - repo init -u $MANIFEST
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - printf "\n\n\n============================\nRepository Berhasil Diunduh, Siap digunakan!!\n============================"
        
