
task:
  name: "Building.."
  timeout_in: 240m  
  container:
      image: anyakichi/aosp-builder:bionic
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - DEBIAN_FRONTEND=noninteractive > /dev/null
       - git config --global user.name "Pakar" > /dev/null
       - git config --global user.email "Pakar@gmail.com" > /dev/null
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/android/os
      - cd ~/android/os
      - repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android/ -b lineage-19.1 -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/ibraaltabian17/local_manifest.git --depth 1 -b 12-dev .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting Testing Tree"
      - echo "============================"
      - cd ~/android/os
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 400G
      - . build/envsetup.sh
      - croot
      - lunch hiper_beryllium-userdebug
      - mka bacon -j8
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd /home/android/os
      - cd out/target/product/beryllium
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file *.zip https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        

