
task:
  name: "Building.."
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt -q update > /dev/null
       - apt -q install sudo > /dev/null
       - DEBIAN_FRONTEND=noninteractive apt-get -q install -y --no-install-recommends tzdata > /dev/null
       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
       - apt-get -q install -y tzdata > /dev/null
       - dpkg-reconfigure --frontend noninteractive tzdata > /dev/null
       - sudo apt -q update -y && sudo apt -q install git aria2 curl wget rsync zip unzip lzma cpio ccache clang jq -y > /dev/null
       - sudo apt -q install python3 -y > /dev/null
       - sudo ln -sf /usr/bin/python3 /usr/bin/python 
       - git config --global user.name "Pakar" > /dev/null
       - git config --global user.email "Pakar@gmail.com" > /dev/null
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts > /dev/null
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh > /dev/null
       - cd ~
       - wget https://raw.githubusercontent.com/ibratabian17/CekRepoAndroid/A6020-Arrow/fakeswap.sh
       - chmod a+x fakeswap.sh
       - ./fakeswap.sh 32024
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/android/os
      - cd ~/android/os
      - repo init --depth=1 --no-repo-verify -u https://github.com/ProjectHiper-ROM/android_manifests -b 11 -g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j31
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/android/os
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 400G
      - . build/envsetup.sh
      - croot
      - lunch hiper_arm-userdebug
      - mka bacon -j31
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd /home/android/os
      - cd out/target/product/beryllium
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file *.zip https://transfer.sh | tee link.txt && echo " "
      - rm -rm *.zip
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        

