env:
    MANIFEST: git://github.com/ProjectHiper-ROM/android_manifests.git -b 11
task:
  name: "Rom Checker"
  timeout_in: 1h
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
      volumes:
        - /home/android:/home/android

        
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
       - apt-get -qq install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt -qq update -y && sudo apt -qq install git aria2 curl wget rsync zip unzip lzma cpio ccache clang -y
       - sudo apt -qq install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "Ibratabian17"
       - git config --global user.email "ibratabian@gmail.com"
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh
       - cd ~
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - printf "\n\n\n============================\nMemulai Cek Repositori\n============================\n"
      - mkdir -p /home/android
      - cd /home/android
      - repo init -u $MANIFEST
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - printf "\n\n\n============================\nRepository Berhasil Diunduh, Siap digunakan!!\n============================"
        
